### ISSUE TITLE
Update to support library 24.0.0

### ISSUE THREAD

**Issue by johan12345** [opacapp/multiline-collapsingtoolbar#10]
Since the last update, multiple new versions of the Support Library have been released (up to 23.4.0). We should check if there were any changes to the classes we copied into this library and update those accordingly in addition to setting the dependency to the newest version in the `build.gradle` file.

However, it seems like the git repository at https://github.com/android/platform_frameworks_support is not updated yet. So we probably need to use the source code downloaded from the Android SDK manager for this.

**Comment by fbarthelery** [comment]
Since support-24.0.0 the library does not work anymore

**Comment by johan12345** [comment]
Oh, thank you for the heads-up on this! I hope we'll find time to update the library with changes up to version 24 soon, as we also intend to update to the newest support library in our app.

**Comment by johan12345** [comment]
I have started this on the `support-24` branch.
