### ISSUE TITLE
How to set MaxLine?

### ISSUE THREAD

**Issue by snzang** [opacapp/multiline-collapsingtoolbar#11]
How to set MaxLine?

**Comment by raphaelm** [comment]
Currently, this is hardcoded to three lines. We'd be happy to accept pull requests that make this configurable.

**Comment by johan12345** [comment]
Actually, it seems this has already been implemented by https://github.com/zsolt-szecsi/multiline-collapsingtoolbar/commit/9779fdd31e2bb1a6587722ea511c8dc0ff9d03a2.

@zsolt-szecsi, did you test if your change works and if so, would you like to open a Pull Request? It might also make sense to rename your `maxNumberOfLines` XML attribute to `maxLines` to make the naming consistent with e.g. `TextView`'s `maxLines` property.

**Comment by johan12345** [comment]
As he didn't reply, I now merged and tested @zsolt-szecsi 's changes by myself. I also renamed the attribute from `maxNumberOfLines` to `maxLines` and made it possible to set them programmatically using a `setMaxLines(int)` method. This feature will be included in the next release, which we will upload to JCenter soon.

**Comment by raphaelm** [comment]
Update 1.2.0 is released. )
