### ISSUE TITLE
Android 4.4: Transition Title does not update

### ISSUE THREAD

**Issue by schlesingermatthias** [opacapp/multiline-collapsingtoolbar#13]
Hi, 
firstly, thanks for you great work. Unfortunately I ran into an issue using your library on an Android 4.4 device (the issue does not occure on 5.0 or higher). The title of the CollapsingToolbarLayout is updated multiple times during the lifetime of the layout. While the expanded and collapsed title change accordingly the title that is displayed during the transition is always the first ever set. 

So here's an example: 
Expanded Title: This is my long title
Transition Title (while scrolling up or down): This is my long title 
Collapsed Title: This is my long title

Than I want to set another title (happens on update of the fragment)
Expanded Title: My other title is also nice
Transition Title: This is my long title
Collapsed Title: My other title is also nice 

See the attached image. The title that was first set ("U11-Mannschaft des SV Reutte...") shows up during the transition of the current title ("Kürzlich wurde im Beisein zahlreicher Ehrengäste...").
![bug](https://cloud.githubusercontent.com/assets/20062071/16222454/5e958768-3798-11e6-9b57-ef8deecd631b.jpg)

Thanks in advance.

**Comment by johan12345** [comment]
Thank you for the bug report! The issue should be fixed with commit 763c0a0 and the next release that we will publish to JCenter soon.

**Comment by raphaelm** [comment]
Update 1.2.0 is released. )

**Comment by schlesingermatthias** [comment]
Awesome. Thanks a ton guys!
