### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by blennerSilva** [opacapp/multiline-collapsingtoolbar#23]
hey huys im using android studio RC 2.2 and im having troubles importing the toolbar

i already put the correct toolbar on the xml but when i try to import the packege on the activity everything goes red and i can import nothing else

**Comment by raphaelm** [comment]
Could you please give us how you import it and what the exact error message looks like?

**Comment by blennerSilva** [comment]
well all i did was to put de dependency on gradle as soon as it compiles my whole project gets red.... then o go to the xml and put the tag and try to change the import on the activity and it doenst work

**Comment by raphaelm** [comment]
Please, show us what you changed. There also will be an error message somewhere, please go and search for it.

**Comment by blennerSilva** [comment]
![screenshot from 2016-09-12 16-06-02](https://cloud.githubusercontent.com/assets/10924301/18448870/1e2a48b0-7903-11e6-951f-f3b54ea14ca9.png)
![screenshot from 2016-09-12 16-06-41](https://cloud.githubusercontent.com/assets/10924301/18448881/2f6aa4b2-7903-11e6-80d7-c5e9926f6982.png)
![screenshot from 2016-09-12 16-07-04](https://cloud.githubusercontent.com/assets/10924301/18448885/3260f9e6-7903-11e6-8276-5c9646e1275c.png)

**Comment by blennerSilva** [comment]
there are no errors... just that

**Comment by johan12345** [comment]
When you hover over the red text, it should show an error message. Have you already tried to rebuild the project (hammer icon in the top bar)?

**Comment by blennerSilva** [comment]
![screenshot from 2016-09-12 16-17-02](https://cloud.githubusercontent.com/assets/10924301/18449125/6b4dd002-7904-11e6-902a-0a40dfafa0af.png)
![screenshot from 2016-09-12 16-17-13](https://cloud.githubusercontent.com/assets/10924301/18449128/6e5ce2ce-7904-11e6-9dd6-337ac530811f.png)
![screenshot from 2016-09-12 16-17-20](https://cloud.githubusercontent.com/assets/10924301/18449131/7159ce92-7904-11e6-975a-6a4c0cebdc89.png)

**Comment by johan12345** [comment]
What is the `import` line you changed? It should be
```java
import net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout;
```

Or maybe you have to sync the Gradle project? -> Open the Gradle tool window (button in the bottom right) and then click the blue "sync" button?

**Comment by blennerSilva** [comment]
well guys i solved ....had to  switch IDE i was using 2.2 RC switched to 2.1.3

**Comment by johan12345** [comment]
Well, it does work for me in 2.2 RC 2...

**Comment by blennerSilva** [comment]
i will download the latested version of rc ...thank you so much for the attention
