### ISSUE TITLE
How to use this library using setTittle

### ISSUE THREAD

**Issue by KamilPieta** [opacapp/multiline-collapsingtoolbar#24]
Im trying to use yours library, but I need to set the tittle dynamiclly. Is there a way to do it? 
```
CollapsingToolbarLayout mCollapsingToolbarLayout=(CollapsingToolbarLayout) findViewById(R.id.collapsing);
        mCollapsingToolbarLayout.setTitle(s);
```
That lines make a ClassCastException of course.

In your demo file you setup the tittle by paramter aapp:title="@string/title", but as far as I know @string values are immutable

**Comment by johan12345** [comment]
You can just `import net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout;`, see #18
