### ISSUE TITLE
Scrim color doesn't persist

### ISSUE THREAD

**Issue by CredM** [opacapp/multiline-collapsingtoolbar#39]
Hi, thanks for this great lib,

I just had an issue when using it. When the toolbar is collapsed, the color doesn't change to the scrim color. It just "blinks" one time, and then remains transparent.

Have you experienced this behavior ?

**Comment by CredM** [comment]
The bug is fixed since your last release (1.4.0). 
Thanks !

**Comment by raphaelm** [comment]
Good to know, thanks for the notice!
