### ISSUE TITLE
Text get duplicated if it's not in English

### ISSUE THREAD

**Issue by HosniMansour** [opacapp/multiline-collapsingtoolbar#40]
When using a no English text title the multi lines works but the text get duplicated in the first line like the image show and it back to normal when it is collapsed

![screenshot_20170427-202937](https://cloud.githubusercontent.com/assets/14791602/25500979/f3a9762c-2b88-11e7-80b5-d7c19c6f6602.png)

**Comment by johan12345** [comment]
This is a duplicate of #33.
