### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rizkideddy** [opacapp/multiline-collapsingtoolbar#47]
ive got error with this :
net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout cannot be cast to android.support.design.widget.CollapsingToolbarLayout

**Comment by johan12345** [comment]
When you interact with the multiline-collapsingtoolbar in Java code, you need to import `net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout` instead of `android.support.design.widget.CollapsingToolbarLayout`. That should fix this error.

**Comment by rizkideddy** [comment]
yes, thank you, thats fixed the error
