### ISSUE TITLE
Link versions to support library dependency version

### ISSUE THREAD

**Issue by giljulio** [opacapp/multiline-collapsingtoolbar#52]
For example:

if `multiline-collapsingtoolbar` depends support lib version `27.x.x` then version the library to `27.[0...9].[0...9]`

This will make it clearer what `multiline-collapsingtoolbar` version depends on which support library version

**Comment by johan12345** [comment]
Yeah, that makes sense. Applying this to previous releases would probably break other people's builds, but we can of course do this for future updates.

**Comment by johan12345** [comment]
Our newest release is now named `27.1.0`, following this convention.

**Comment by johan12345** [comment]
It seems that Google is going to rename the support libraries to the *AndroidX* libraries and start from version `1.0.0` again with the next release ([link](https://developer.android.com/topic/libraries/support-library/androidx-rn)) - so we're going to need to think about how we will name our library versions now. Maybe start with `X1.0.0` then?
