### ISSUE TITLE
Update library to Support Library version 27.1.1

### ISSUE THREAD

**Issue by PattaFeuFeu** [opacapp/multiline-collapsingtoolbar#55]
https://developer.android.com/topic/libraries/support-library/revisions.html

The new Support Library version 27.1.1 is just out

**Changes**:

- AsyncListDiffer doesn't call getChangePayload (AOSP issue 73961809)
- Fragment ViewModel's onCleared not called (AOSP issue 74139250)
- RecyclerView.setRecycledViewPool() increases attachCount even when adapter is null
- RecyclerView NPE if SmoothScroller.onStop calling stop() or startSmoothScroller()
- Fragment Replacement transaction causes previous fragment to flicker after new fragment is shown (AOSP issue 74051124)
- Loader callback breaking change in 27.1.0 (AOSP issue 74135998)
- RTL layout does not work when the vertical grid view set column >1
- onLoadFinished called multiple times in ViewPager with FragmentPagerAdapter
- AsyncListDiffer should dispatch updates after setting current list (AOSP issue 74003309)
- ShareActionProvider throws ClassCastException in 27.1.0
- Fragment lifecycle change with ViewPager (AOSP issue 73976255)

**Comment by johan12345** [comment]
I have uploaded a new version `27.1.1`. :)
This time, it was quite easy since nothing was changed in the design support library with the 27.1.1 release.
