### ISSUE TITLE
JCenter migration

### ISSUE THREAD

**Issue by npace** [opacapp/multiline-collapsingtoolbar#66]
Hello,

As you may be aware, Bintray and JCenter are being sunset on May 1st 2021 ([announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)).

Are there any plans to migrate this library to Maven Central before JCenter goes offline?

Thanks!

**Comment by raphaelm** [comment]
I'm actually not sure if we're investing the effort to do that since the library is kinda deprecated since the functionality is included in the official libraries now. For legacy users jitpack will probably be good-enough?

**Comment by npace** [comment]
Wow, thanks for the quick reply!

Jitpack would be good for sure. I already use it for some other dependencies.

BTW since you said that this library is basically deprecated, do you have any alternative libraries in mind? 
Either way, my use case is in some legacy code so I can just keep using this one for the foreseeable future...

**Comment by raphaelm** [comment]
The alternative is the actual material components library from Google which accepted the main part of this library as a patch: https://github.com/material-components/material-components-android/pull/413

**Comment by npace** [comment]
Hmm, it looks like there's no point in _not_ using the material components version. I guess that makes migrating this library redundant. Thanks again!
